jobs:
  Explorando-GitHub-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir información del evento
        run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"
      
      - name: Imprimir información del sistema operativo
        run: echo "El trabajo se está ejecutando en un servidor ${{ runner.os }} hospedado en GitHub"
      
      - name: Imprimir información de la rama
        run: echo "El nombre de la rama es: ${{ github.ref }} y tu repositorio es: ${{ github.repository }}."
      
      - name: Verifica el código del repositorio
        uses: actions/checkout@v2
      
      - name: Imprimir confirmación de clonado
        run: echo "El repositorio: ${{ github.repository }} ha sido clonado al runner."
      
      - name: Preparación para la verificación de código
        run: echo "El flujo de trabajo está listo para verificar el código en el runner."
      
      - name: Listar archivos en el repositorio
        run: ls ${{ github.workspace }}
      
      - name: Imprimir estado del trabajo
        run: echo "El estado del trabajo es: ${{ job.status }}."
